version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ../Backend/artperspective
      dockerfile: Dockerfile
    volumes:
      - ../Backend/artperspective:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 8080

  frontend-builder:
    build:
      context: ../Frontend
      dockerfile: Dockerfile   # в нём только стадия builder
      target: builder
    volumes:
      - frontend_dist:/app/dist
    command: ["sh", "-c", "npm ci --legacy-peer-deps --silent && npm run build"]
    # контейнер отработает и завершится

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend-builder

volumes:
  pgdata:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local
  frontend_dist:
    driver: local