# Generated by Django 5.2.1 on 2025-05-18 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paintings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.painting'),
        ),
        migrations.AddField(
            model_name='paintingtag',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.painting'),
        ),
        migrations.AddField(
            model_name='paintingtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.tags'),
        ),
        migrations.AddField(
            model_name='painting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='paintings', through='paintings.PaintingTag', to='paintings.tags'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'painting'), name='unique_favorite'),
        ),
        migrations.AddIndex(
            model_name='paintingtag',
            index=models.Index(fields=['tag', 'painting'], name='paintings_p_tag_id_930dc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paintingtag',
            unique_together={('painting', 'tag')},
        ),
    ]
