# Generated by Django 5.2.1 on 2025-05-18 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя художника')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('image', models.ImageField(upload_to='artists/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Картина', 'verbose_name_plural': 'Картины'},
        ),
        migrations.AlterModelOptions(
            name='paintingtag',
            options={'verbose_name': 'Тег картины', 'verbose_name_plural': 'Теги картин'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.painting', verbose_name='Картина'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='В архиве'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='paintings/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='paintings', through='paintings.PaintingTag', to='paintings.tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.IntegerField(verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='paintingtag',
            name='painting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.painting', verbose_name='Картина'),
        ),
        migrations.AlterField(
            model_name='paintingtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.tags', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.artist', verbose_name='Художник'),
        ),
    ]
