# Generated by Django 5.2.1 on 2025-05-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0003_artist_alter_painting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='paintings.artist', verbose_name='Художник'),
        ),
    ]
