# Generated by Django 5.2.1 on 2025-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_alter_painting_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='background',
            field=models.ImageField(blank=True, upload_to='artists/backgrounds/', verbose_name='Фоновое изображение'),
        ),
    ]
